### ISSUE TITLE
Test and CI proposal

### ISSUE THREAD

**Issue by scriptnull** [argonlaser/go-isdocker#2]
# Test Architecture

Right now testing is done only for NonDocker process, we need to test process running inside an actual container.

 So my proposal is having two separate tests for this.

When running the CI, we will run two tests in different ways
 
1) func TestNonDockerProcess(t *testing.T)

This will be run on a bash process by executing

```bash
$ go test -run="TestNonDockerProcess"
```
1) func TestDockerProcess(t *testing.T)

This test will be run by following the below steps
- Build a Docker image with go installed and ADD the src repo
- execute the following command inside the container
```bash
$ go test -run="TestDockerProcess"
```

# CI Proposal
We need a CI system, that can run process both on host machine and inside a docker container.

Shippable runs normal CI commands inside a container, instead of host machine. So `TestNonDockerProcess` will fail always.

We need to figure out a CI system, that runs commands on the host machines directly.

**Comment by argonlaser** [comment]
Thanks a lot for the valuable suggestions @scriptnull . As you said, I have added ```semaphore``` CI for non-docker as they run in virtual machine and ```travis``` CI for docker checks. I think we can close the issue.
